In [1]:
import torch as t

In [6]:
import torch as t
t.abs(t.FloatTensor([-1,-2,3]))

tensor([1., 2., 3.])

In [9]:
import torch as t
a = t.Tensor(3,4)
%timeit a.sum()

4.3 µs ± 77.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%hist

%matplotlib inline
torch.abs(torch.FloatTensor([-1,-2,3]))
t.abs(torch.FloatTensor([-1,-2,3]))
t.abs(torch.FloatTensor([-1,-2,3]))
import torch as t
t.abs(torch.FloatTensor([-1,-2,3]))
import torch as t
t.abs(t.FloatTensor([-1,-2,3]))
import torch as t
a = t.Tensor(3,4)
%timeit a.sum()
import torch as t
a = t.Tensor(3,4)
%timeit a.sum()
import torch as t
a = t.Tensor(3,4)
%timeit a.sum()
%hist


In [11]:
%paste

UsageError: Line magic function `%paste` not found.


In [13]:
def add(x,y,z):
    return x+y+z

a = add(1,2,3)
print(a)

6


In [14]:
a=t.Tensor(3,4)

In [16]:
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [17]:
a = t.Tensor(5,5)
print(a)

tensor([[-3.1170e+31,  4.6523e-43,  7.9874e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.8754e+28,  2.0110e+20,  2.6254e-06,  1.0074e-11,  3.3063e-09],
        [ 8.2656e-10,  2.6076e+20,  2.0448e+23,  8.1994e-10,  8.1253e+20],
        [ 5.1247e-11,  4.2330e+21,  1.6534e+19,  3.0478e+32,  1.6255e-43]])


In [18]:
%xdel

In [19]:
import torch as t

In [20]:
out[17]

NameError: name 'out' is not defined

In [21]:
Out[17]

KeyError: 17

In [3]:
from __future__ import print_function
import torch as t

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5246e-42, 0.0000e+00],
        [0.0000e+00, 6.2609e+22, 0.0000e+00]])

In [4]:
x = t.Tensor(5,3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5246e-42, 0.0000e+00],
        [0.0000e+00, 6.2609e+22, 0.0000e+00]])

In [5]:
x = t.rand(5,3)

In [6]:
x

tensor([[0.7154, 0.9276, 0.2618],
        [0.8008, 0.5568, 0.5696],
        [0.9809, 0.3223, 0.8796],
        [0.2431, 0.2358, 0.6890],
        [0.8338, 0.9022, 0.9812]])

In [10]:
print(x.size()[0])

5


In [11]:
print(x.size(1))

3


In [12]:
print(x.size()[0])

5


In [13]:
x.size()[0],x.size(1)

(5, 3)

In [14]:
y = t.rand(5,3)
x+y

tensor([[1.4116, 1.5465, 0.7067],
        [1.6620, 1.0400, 1.5510],
        [1.9570, 0.4588, 1.1700],
        [0.8217, 0.9110, 0.8630],
        [0.8820, 1.7762, 1.8040]])

In [15]:
t.add(x+y)

TypeError: add() received an invalid combination of arguments - got (Tensor), but expected (Tensor input, Tensor other, Number alpha, Tensor out)

In [16]:
t.add(x,y)

tensor([[1.4116, 1.5465, 0.7067],
        [1.6620, 1.0400, 1.5510],
        [1.9570, 0.4588, 1.1700],
        [0.8217, 0.9110, 0.8630],
        [0.8820, 1.7762, 1.8040]])

In [17]:
result = t.Tensor(5,3)
t.add(x,y,out = result)
result

tensor([[1.4116, 1.5465, 0.7067],
        [1.6620, 1.0400, 1.5510],
        [1.9570, 0.4588, 1.1700],
        [0.8217, 0.9110, 0.8630],
        [0.8820, 1.7762, 1.8040]])

In [18]:
print('orininal y')
print(y)

y.add(x)
print(y)

y.add_(x)
print(y)

orininal y
tensor([[0.6962, 0.6189, 0.4449],
        [0.8612, 0.4832, 0.9814],
        [0.9762, 0.1366, 0.2904],
        [0.5786, 0.6752, 0.1740],
        [0.0482, 0.8740, 0.8228]])
tensor([[0.6962, 0.6189, 0.4449],
        [0.8612, 0.4832, 0.9814],
        [0.9762, 0.1366, 0.2904],
        [0.5786, 0.6752, 0.1740],
        [0.0482, 0.8740, 0.8228]])
tensor([[1.4116, 1.5465, 0.7067],
        [1.6620, 1.0400, 1.5510],
        [1.9570, 0.4588, 1.1700],
        [0.8217, 0.9110, 0.8630],
        [0.8820, 1.7762, 1.8040]])


In [19]:
x[:,1]

tensor([0.9276, 0.5568, 0.3223, 0.2358, 0.9022])

In [20]:
print(x)

tensor([[0.7154, 0.9276, 0.2618],
        [0.8008, 0.5568, 0.5696],
        [0.9809, 0.3223, 0.8796],
        [0.2431, 0.2358, 0.6890],
        [0.8338, 0.9022, 0.9812]])


In [21]:
a = t.ones(5)

In [22]:
a

tensor([1., 1., 1., 1., 1.])

In [23]:
size(a)

NameError: name 'size' is not defined

In [24]:
a.size()

torch.Size([5])

In [25]:
b = a.numpy()

In [26]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [27]:
import numpy as np

In [28]:
a = np.ones(5)
b = t.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [29]:
b.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [2]:
from torch.autograd import Variable
import torch as t
x = Variable(t.ones(2,2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [4]:
y.grad_fn

In [6]:
x.grad

In [16]:
y.backward()

In [17]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [15]:
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [18]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
        
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = x.view(x.size()[0],-1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [1]:
input = Variable(t.randn(1,1,32,32))
print(input)

NameError: name 'Variable' is not defined

In [1]:
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import torch as t

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(x.size()[0], -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
print(net)

params = list(net.parameters())
print(len(params))

# 查看有哪些参数
for name,parameters in net.named_parameters():
    print(name,":", parameters.size())

# nSamples*nChannels*Height*Width
input = Variable(t.randn(1, 1, 32, 32))
# 前向传播
# out = net(input)
# print(out.size())
# net.zero_grad()
# # 反向传播
# out.backward(Variable(t.ones(1, 10)))

output = net(input)
target = Variable(t.arange(0, 10))
# 损失函数
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
10
conv1.weight : torch.Size([6, 1, 5, 5])
conv1.bias : torch.Size([6])
conv2.weight : torch.Size([16, 6, 5, 5])
conv2.bias : torch.Size([16])
fc1.weight : torch.Size([120, 400])
fc1.bias : torch.Size([120])
fc2.weight : torch.Size([84, 120])
fc2.bias : torch.Size([84])
fc3.weight : torch.Size([10, 84])
fc3.bias : torch.Size([10])


RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #2 'target'

In [1]:
from notebook.auth import passwd
passwd()
m=2
print "here %s" %m

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("here %s" %m)? (<ipython-input-1-26955d3b4df5>, line 4)

In [2]:
from notebook.auth import passwd
passwd()

StdinNotImplementedError: getpass was called, but this frontend does not support input requests.

In [3]:
m=2
print("here %s", %m)

SyntaxError: invalid syntax (<ipython-input-3-957cf206e5d2>, line 2)

In [1]:
print('Hello, %s' % 'world')

Hello, world


In [6]:
m=2
n=3
print ("here",m," is ", n)

here 2  is  3


In [2]:
print('Age: %s. Gender: %s' % (25, True))

Age: 25. Gender: True


In [3]:
print('Age:', 25, '. Gender: ', 'True')

Age: 25 . Gender:  True


In [6]:
classmates = ['Michael', 'Bob', 'Tracy']
classmates

['Michael', 'Bob', 'Tracy']

In [7]:
classmates[2]

'Tracy'

In [8]:
classmates[-3]

'Michael'

In [9]:
classmates.append('Lucy')
len(classmates)

4

In [10]:
classmates.insert(1,'Mike')
classmates

['Michael', 'Mike', 'Bob', 'Tracy', 'Lucy']

In [11]:
classmates.pop() #删除末尾元素

'Lucy'

In [12]:
classmates.pop(1)
classmates

['Michael', 'Bob', 'Tracy']

In [14]:
t=(1,)
t

(1,)

In [15]:
L = [
    ['Apple', 'Google', 'Microsoft'],
    ['Java', 'Python', 'Ruby', 'PHP'],
    ['Adam', 'Bart', 'Lisa']
]
print(L[1][1])

Python


In [17]:
age = 3
if age >= 18:
    print('adult')
elif age >= 6:
    print('teenager')
else:
    print('kid')
# 从上往下判断，如果在某个判断上是True，把该判断对应的语句执行后，就忽略掉剩下的elif和elsle


kid


In [18]:
s = input('birth: ')
birth = int(s)
if birth < 2000:
    print('00前')
else:
    print('00后')

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

In [1]:
int(12.22)

12

In [2]:
a = abs
a(-1)

1

In [3]:
n1 = 255 
n2 = 1000
print(hex(n1))

0xff


In [6]:
# from .py文件 import 函数
def my_abs(x):
    if not isinstance(x,(int, float)):
        raise TypeError('Bad operand type')
    if x >= 0:
        return x
    else:
        return -x
    

my_abs(-3)


3

In [7]:
def add_end(L=None):
    if L is None:
        L = []
    L.append('End')
    return L

add_end()


['End']

In [8]:
def calc(numbers):
    sum = 0
    for n in numbers:
        sum = sum + n * n
    return sum

calc([1,2,3])

14

In [9]:
a = [1,2,3]
calc(a)

14

In [10]:
def calc(*numbers):
    sum = 0
    for n in numbers:
        sum = sum + n * n
    return sum
calc(a)

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
calc(*a)

14

In [12]:
calc()

0

In [13]:
calc(1,2)

5

In [14]:
def person(name, age, **kw):
    print('name:', name, 'age:', age, 'other:', kw)
    
person('Michael', 30, city='Beijing')

name: Michael age: 30 other: {'city': 'Beijing'}


In [16]:
person('Mike',35,job='lawer', city='Beijing')

name: Mike age: 35 other: {'job': 'lawer', 'city': 'Beijing'}


In [17]:
extra = {'city': 'Beijing', 'job': 'Engineer'}
person('Jack', 24, **extra)

name: Jack age: 24 other: {'city': 'Beijing', 'job': 'Engineer'}


In [18]:
def person(name, age, *, city, job):
    print(name, age, city, job)
    

In [19]:
person('Jack', 24, city='Beijing', job='Engineer')


Jack 24 Beijing Engineer


In [38]:
def product(*args):
    # 异常处理
    if len(args) == 0:
        raise TypeError('Bad operand type')
    sum = 1
    for x in args:
        sum = sum * x
    return sum

print('product(5) =', product(5))
print('product(5, 6) =', product(5, 6))
print('product(5, 6, 7) =', product(5, 6, 7))
print('product(5, 6, 7, 9) =', product(5, 6, 7, 9))
if product(5) != 5:
    print('测试失败!1')
elif product(5, 6) != 30:
    print('测试失败!2')
elif product(5, 6, 7) != 210:
    print('测试失败!3')
elif product(5, 6, 7, 9) != 1890:
    print('测试失败!4')
else:
    try:
        product()
        print('测试失败!')
    except TypeError:
        print('测试成功!')

product(5) = 5
product(5, 6) = 30
product(5, 6, 7) = 210
product(5, 6, 7, 9) = 1890
测试成功!


In [34]:
product()

()


In [40]:
def fact(n):
    if n == 1:
        return 1
    return n * fact(n-1)

In [48]:
# 将上面递归改成尾递归模式：
def fact(n):
    return fact_iter(n,1)

def fact_iter(num, product):
    if num == 1:
        return product
    return fact_iter(num-1, num*product)


In [47]:
fact_iter(3,9)

54

In [49]:
def move(n,a,b,c):
    if n == 1:
        print(a, '-->', c)
        return 
    else:
        # 先将a的n-1个盘放到b，将a的最后一个移到c，将b的n-1移到c
        move(n-1, a, c, b)
        move(1, a, b, c)
        move(n-1, b, a, c)

move(3, 'A', 'B', 'C')

A --> C
A --> B
C --> B
A --> C
B --> A
B --> C
A --> C


In [53]:
L = ['Michael', 'Sarah', 'Tracy', 'Bob', 'Jack']
r = []
n = 3
for i in range(n):
    r.append(L[i])
p = L[0:3]  # 0,1,2
p = L[-2:]
p

['Bob', 'Jack']

In [1]:
def trim(s):
    i = 0
    j = 0
    for i in range(len(s)):
        if s[i] != ' ':
            break
    for j in range(len(s)):
        j = j+1
        if s[-j] != ' ':
            break
    return s[i:(len(s)-j+1)]


# 测试:
if trim('hello  ') != 'hello':
    print('测试失败!')
elif trim('  hello') != 'hello':
    print('测试失败!')
elif trim('  hello  ') != 'hello':
    print('测试失败!')
elif trim('  hello  world  ') != 'hello  world':
    print('测试失败!')
elif trim('') != '':
    print('测试失败!')
elif trim('    ') != '':
    print('测试失败!')
else:
    print('测试成功!')

测试成功!


In [4]:
def findMinAndMax(L):
    if len(L) == 0:
        return (None, None)
    mintmp = L[0]
    maxtmp = L[0]
    for x in L:
        if x > maxtmp:
            maxtmp = x
        if x < mintmp:
            mintmp = x
    return (mintmp, maxtmp)

if findMinAndMax([]) != (None, None):
    print('测试失败!')
elif findMinAndMax([7]) != (7, 7):
    print('测试失败!')
elif findMinAndMax([7, 1]) != (1, 7):
    print('测试失败!')
elif findMinAndMax([7, 1, 3, 9, 5]) != (1, 9):
    print('测试失败!')
else:
    print('测试成功!')

测试成功!


In [5]:
[x*x for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [6]:
[x*x for x in range(1, 11) if x%2 == 0]

[4, 16, 36, 64, 100]

In [9]:
[m+n for m in 'ABC' for n in 'XYZ']

['AX', 'AY', 'AZ', 'BX', 'BY', 'BZ', 'CX', 'CY', 'CZ']

In [10]:
import os
# 列出当前目录下文件和目录名
[d for d in os.listdir('.')]

['.idea', 'cifar-10-python', 'CIFAR_LeNet.py', 'Test1.py', 'testJupyter.ipynb']

In [12]:
d = {'x':'A','y':'B','z':'C'}
for k, v in d.items():
    print(k, '=', v)
    
[k + '=' + v for k, v in d.items()]

x = A
y = B
z = C


['x=A', 'y=B', 'z=C']

In [17]:
g = (x*x for x in range(10))
next(g)
next(g)

1

In [20]:
next(g)

16

In [21]:
for n in g:
    print(n)

25
36
49
64
81


In [29]:
def triangles():
    # 每个是一个list
    L, index = [1], 0
    while True:
        yield L
        # L = [1] + [L[i] + L[i+1] for i in range(len(L)-1)] + [1]
        # L.append(0) # 执行results.append(t)的时候，由于results.append(t)的参数t是引用传递，所以此时results这个大list中的小list和t指向的List是同一个地址。
        # L[-1] 是最后一个
        L = L + [0]
        L = [L[i-1] + L[i] for i in range(len(L))]
        

n = 0
results = []
for t in triangles():
    print(t)
    results.append(t)
    n = n + 1
    if n == 10:
        break
if results == [
    [1],
    [1, 1],
    [1, 2, 1],
    [1, 3, 3, 1],
    [1, 4, 6, 4, 1],
    [1, 5, 10, 10, 5, 1],
    [1, 6, 15, 20, 15, 6, 1],
    [1, 7, 21, 35, 35, 21, 7, 1],
    [1, 8, 28, 56, 70, 56, 28, 8, 1],
    [1, 9, 36, 84, 126, 126, 84, 36, 9, 1]
]:
    print('测试通过!')
else:
    print('测试失败!')

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
[1, 7, 21, 35, 35, 21, 7, 1]
[1, 8, 28, 56, 70, 56, 28, 8, 1]
[1, 9, 36, 84, 126, 126, 84, 36, 9, 1]
测试通过!


In [34]:
def f(x):
    return x*x

r = map(f, [1,2])
list(r)

[1, 4]

In [36]:
def normalize(name):
    name = name[0].upper() + name[1:].lower()
    return name

# 测试:
L1 = ['adam', 'LISA', 'barT']
L2 = list(map(normalize, L1))
print(L2)

['Adam', 'Lisa', 'Bart']


In [38]:
from functools import reduce
def prod(L):
    def f(x, y):
        return x * y
    return(reduce(f, L))

print('3 * 5 * 7 * 9 =', prod([3, 5, 7, 9]))
if prod([3, 5, 7, 9]) == 945:
    print('测试成功!')
else:
    print('测试失败!')

3 * 5 * 7 * 9 = 945
测试成功!


In [51]:
DIGIT = {'0':0, '1':1, '2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9 }
def str2float(s):
    def char2int(s):
        return DIGIT[s]
    def prod(x,y):
        return x*10+y
    a = reduce(prod, map(char2int, s.replace('.','')))
    # for i in range(len(s)):
    #     if s[i] == '.':
    #         a = a/(10**(len(s)-i-1))
    #         break
    if s.find('.') != -1:
        a = a/(10**(len(s) - s.find('.') - 1))
    return a   

print('str2float(\'123.456\') =', str2float('123.456'))
if abs(str2float('123.456') - 123.456) < 0.00001:
    print('测试成功!')
else:
    print('测试失败!')

str2float('123.456') = 123.456
测试成功!


In [54]:
L = [('Bob', 75), ('Adam', 92), ('Bart', 66), ('Lisa', 88)]
def by_name(t):
    return t[0]

L2 = sorted(L, key=by_name)
print(L2)

[('Adam', 92), ('Bart', 66), ('Bob', 75), ('Lisa', 88)]


In [17]:

def threeSum(nums):
    nums.sort()
    # print(nums)
    if len(nums) < 3 or nums[0] > 0 or nums[-1] < 0:
        return []
    L = []
    k = 0
    while True:
        if k >= len(nums)-2:
            break
        if nums[k] > 0:
            break
        if nums[k] == nums[k+1]:
            k = k+1
            continue
        target = 0 - nums[k]
        print(k)
        i = k+1
        j = len(nums)-1
        while i<j:
            print([i,j])
            if nums[i]+nums[j] == target:
                tmp = [nums[k], nums[i], nums[j]]
                L.append(tmp)                
                print(L)
                while i < j and nums[i] == nums[i+1]:
                    print(1)
                    i = i + 1
                while i < j and nums[j] == nums[j-1]:
                    print(2)
                    j = j - 1  
                i = i + 1
                j = j - 1
            elif nums[i]+nums[j] < target:
                i = i + 1
            else:
                j = j - 1
        k = k + 1
    return L
a = [-1,0,1,2,-1,-4]
print (threeSum(a))

0
[1, 5]
[2, 5]
[3, 5]
[4, 5]
2
[3, 5]
[3, 4]
[[-1, 0, 1]]
3
[4, 5]
[[-1, 0, 1]]


In [22]:
def is_odd(n):
    return n % 2 == 1
L = list(filter(is_odd, range(1, 20)))
L=list(filter(lambda n:n%2==1,range(1,20)))
print(L)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [54]:
import torch as t
b = t.Tensor([[1.1,2,3], [4,5,6]])
b.size()

torch.Size([2, 3])

In [79]:
b.tolist()
b # b还是Tensor
b.size()
b.numel()
b.nelement()
c = t.Tensor(b.size())
d = t.Tensor((2, 3))  # 元素为2和3的tensor
e = t.Tensor(2, 3)  # 指定形状
f = t.tensor(b.size())
e.type(), f.type()
e.size()[0]  #行 1列

2

In [66]:
import numpy as np
a=np.zeros(2,dtype=np.float64)
a=t.tensor(a)
a.type()


'torch.DoubleTensor'

In [76]:
a = t.arange(1,6,2)  #生成1:2:6
a.size()[0]  # 行

3

In [83]:
a = t.linspace(1,10,3)
a

tensor([ 1.0000,  5.5000, 10.0000])

In [87]:
a = t.randperm(5)  # 长度为5的随机排列
a = t.eye(2,3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [119]:
a = t.arange(0, 6)
b = a.view(2, 3)
b = a.view(-1, 2)  # 某一维为-1，自动根据后面计算大小
c = b.unsqueeze(1) # 在第一维上（下标从0开始）增加一维 (-2)倒数第二维
c.size()
c = b.unsqueeze(2) 
c.size()
c = b.view(1,1,1,2,3)
# 压缩第0维
d = c.squeeze(0)
c.size(), d.size()
c, d
e = c.squeeze()  # 把所有维度为1的压缩
e, e.size()
a[1] = 100  # a,b共享内存，a修改 b也修改
b
b.resize_(1,3)
b.resize_(3,3)  # 旧的数据依旧保存，新的数据分配新空间

tensor([[            0,           100,             2],
        [            3,             4,             5],
        [2624225017856,             0,             0]])

In [127]:
a = t.randn(2,3)
a
a[0]  # 第0行
a[:, 0]  # 第0列 都以行显示
a, a[0][2]


(tensor([[-0.4080,  0.6200, -0.9083],
         [-0.8596, -0.7597, -1.0442]]), tensor(-0.9083))

In [138]:
a[0,-1]
a[:2]  # 前两行
print(a[:1,:2])  # 前一行的前两列
a>1
b = a[a>1]
b

tensor([[-0.4080,  0.6200]])


tensor([])

In [162]:
a = t.arange(0.0,16.0).view(4,4)
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [164]:
index = t.LongTensor([[0,1,2,3]])
a.gather(0, index)  # 第n列的第几个
index = t.LongTensor([[1,1,1,1]]).t()
a.gather(1, index)  # 第n行的第几个
index = t.LongTensor([[3,2,1,0]])
a.gather(0, index)
index = t.LongTensor([[0,1,2,3], [3,2,1,0]]).t()
a.gather(1, index)

tensor([[ 0.,  3.],
        [ 5.,  6.],
        [10.,  9.],
        [15., 12.]])

In [165]:
c = t.zeros(4,4)
c.scatter_(1, index, a)

tensor([[ 0.,  0.,  0.,  1.],
        [ 0.,  4.,  5.,  0.],
        [ 0.,  9.,  8.,  0.],
        [13.,  0.,  0., 12.]])

In [170]:
a = np.ones([2,3], dtype = np.float32)
b = t.from_numpy(a)
b
b = t.Tensor(a)  # 将numpy对象传入Tensor
a[0, 1] = 100
b

tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]])

In [181]:
a = t.ones(3,2)
b = t.zeros(2,3,1)
a+b
a.unsqueeze(0).expand(2,3,2) + b.expand(2,3,2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [187]:
b = a.clone()  # 改变a不会影响b了，不然共享内存
a[1,1] = 100
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
import torch as t
t.rand(8,1)
t.randn(8, 1)

tensor([[-1.3532],
        [ 0.0795],
        [-1.7854],
        [-0.0291],
        [ 0.4638],
        [-0.1958],
        [-1.6228],
        [ 0.0461]])

In [63]:

import torch as t
from torch.autograd import Variable as V
t.manual_seed(2)
a = V(t.randn(1, 1, 5, 5))
a
from torch import nn
net1 = nn.Sequential()
net1.add_module('conv', nn.Conv2d(1, 5, 4))
net1.add_module('batchnorm', nn.BatchNorm2d(5))
net1.add_module('activation_layer', nn.ReLU())
# for name, parameter in net1.named_parameters():
#     print(name, parameter)
out1 = net1(a)

net2 = nn.Sequential(nn.Conv2d(1, 5, 4), nn.BatchNorm2d(5), nn.ReLU())
# for name, parameter in net2.named_parameters():
#     print(name, parameter)
out2 = net2(a)

from collections import OrderedDict
net3 = nn.Sequential(OrderedDict([('conv', nn.Conv2d(1, 5, 4)),
                      ('bn', nn.BatchNorm2d(5)),
                      ('relu', nn.ReLU())]))
# for name, parameter in net3.named_parameters():
#     print(name, parameter)
out3 = net3(a)
print(a)
print(net1.conv(a))


tensor([[[[-1.0408,  0.9166, -1.3042, -1.1097, -1.2188],
          [ 1.1676, -1.0574, -0.1188, -0.9078,  0.6737],
          [-1.1233, -0.0919, -0.1320, -0.2751, -0.2350],
          [ 0.0937, -0.7650, -1.2425, -0.1752,  0.6990],
          [-0.6861,  0.7202,  0.1963,  0.6142,  1.1566]]]])
tensor([[[[ 0.2520, -0.7195],
          [-1.0020,  0.1968]],

         [[-1.3492, -0.2736],
          [-0.1434, -0.7354]],

         [[-0.4583,  0.7145],
          [ 0.5712,  0.3026]],

         [[ 0.6152,  0.2844],
          [ 0.1094,  0.9915]],

         [[-0.2878, -0.2027],
          [ 0.0955,  0.0613]]]], grad_fn=<ThnnConv2DBackward>)


In [59]:
import torch
from torch.autograd import Variable
##单位矩阵来模拟输入
input = torch.ones(1, 1, 5, 5)
input = Variable(input)
x=torch.nn.Conv2d(1, 5, 4)
out=x(input)
print(out)
print(list(x.parameters()))

tensor([[[[-0.6651, -0.6651],
          [-0.6651, -0.6651]],

         [[ 0.3485,  0.3485],
          [ 0.3485,  0.3485]],

         [[-0.6560, -0.6560],
          [-0.6560, -0.6560]],

         [[-0.4652, -0.4652],
          [-0.4652, -0.4652]],

         [[ 0.3900,  0.3900],
          [ 0.3900,  0.3900]]]], grad_fn=<ThnnConv2DBackward>)
[Parameter containing:
tensor([[[[-0.1286,  0.0100,  0.0513,  0.0661],
          [-0.0141, -0.1308, -0.0077, -0.0691],
          [-0.0839, -0.1239, -0.1212, -0.1178],
          [ 0.0985, -0.2114, -0.2378,  0.2138]]],


        [[[ 0.0897,  0.1383,  0.1091, -0.0954],
          [-0.1570, -0.1704, -0.0158,  0.0620],
          [-0.2342, -0.1920,  0.1407,  0.0321],
          [ 0.1649,  0.2227,  0.1520, -0.0531]]],


        [[[-0.1112,  0.0707,  0.2034, -0.2397],
          [ 0.0671, -0.1927, -0.1988,  0.0905],
          [ 0.1272,  0.0856,  0.0727, -0.0755],
          [ 0.0060, -0.2208, -0.1631,  0.0051]]],


        [[[-0.0573, -0.0389,  0.1421,  0.0939],


In [13]:
x = "data/train/cat.10004.jpg"
# train: data/train/cat.10004.jpg 
imgs = (x.split('.'))
#.split('/')[-1])
imgs

['data/train/cat', '10004', 'jpg']

In [18]:
import time
print(time.strftime('%m_%d_%H:%M:%S'))

02_12_11:19:12


In [2]:
from torchnet import meter

In [ ]:
print("123")